DO $$
DECLARE
    i INT;
BEGIN
    -- Create 300 standard tables
    FOR i IN 1..300 LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS synthetic_table_%s (
                id SERIAL PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                status VARCHAR(20) DEFAULT ''active'',
                value NUMERIC(10, 2)
            );
            CREATE INDEX IF NOT EXISTS idx_synthetic_%s_status ON synthetic_table_%s(status);
            COMMENT ON TABLE synthetic_table_%s IS ''Autogenerated synthetic table %s'';
            COMMENT ON COLUMN synthetic_table_%s.name IS ''Name of the entity'';
        ', i, i, i, i, i, i);
    END LOOP;

    -- Create Edge Case Table with exotic types
    CREATE TABLE IF NOT EXISTS edge_case_table (
        id UUID PRIMARY KEY,
        metadata JSONB,
        ip_addr INET,
        network CIDR,
        mac MACADDR,
        search_vector TSVECTOR,
        coordinates POINT,
        flags BOOLEAN[]
    );
    COMMENT ON TABLE edge_case_table IS 'Table containing rare postgres types';

    -- Create Foreign Keys
    CREATE TABLE IF NOT EXISTS synthetic_child (
        id SERIAL PRIMARY KEY,
        parent_id INT REFERENCES synthetic_table_1(id)
    );

    -- Create Views
    CREATE OR REPLACE VIEW active_synthetic_1 AS
        SELECT * FROM synthetic_table_1 WHERE status = 'active';

END $$;
