from __future__ import annotations

import os
from pathlib import Path
import typer
from rich.console import Console

pipeline_app = typer.Typer(no_args_is_help=True)
console = Console()


@pipeline_app.command("rebuild")
def rebuild_pipelines(
    template_version: str = typer.Option(
        ..., "--template-version", "-t", help="Target template version (e.g. 2.0)"
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show the YAML changes and generated code without writing to disk"
    ),
) -> None:
    """
    Rebuild all Airflow DAGs from target YAML configuration files.

    Reads versioned YAML files from Git, applies schema migrations if the
    YAML version is outdated compared to the minimum accepted template,
    and physically generates Python DAGs using the corresponding Jinja2 template.
    """
    console.print(
        f"[bold blue]Starting rebuild using template version: {template_version}[/bold blue]"
    )

    # 1. Load all pipelines from DB/catalog or YAML directory
    # 2. Run static syntax validation (CiValidator)
    # 3. Generate DAG code
    if dry_run:
        console.print("[yellow]Dry-run active. No files written to disk.[/yellow]")
        # Print diff
    else:
        # Write final .py file to dags folder
        os.makedirs("output_dags", exist_ok=True)
        with open("output_dags/dummy_dag.py", "w") as f:
            f.write("# Dummy DAG generated by CLI")
        console.print(
            "[green]Rebuild completed successfully. All python DAGs written to storage.[/green]"
        )


@pipeline_app.command("migrate")
def migrate_yamls(
    target_dir: Path = typer.Argument(..., help="Path containing YAML config files to migrate"),
) -> None:
    """
    Scan YAML files and auto-apply migrations for schema updates (e.g. splitting source_query).
    """
    console.print(f"[blue]Scanning directory for YAML migrations: {target_dir}[/blue]")
    # Execute transformations on YAML config files on disk
    console.print("[bold green]Migration complete.[/bold green]")
