"""add_idempotency_key_and_pipeline_run_files

Revision ID: 14f90f1ed51b
Revises: f7d6f51e45d7
Create Date: 2026-09-22 10:16:14.359486

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14f90f1ed51b"
down_revision: str | Sequence[str] | None = "f7d6f51e45d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_run_files",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pipeline_run_id", sa.String(length=36), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hash_md5", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pipeline_run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pipeline_run_files", schema=None) as batch_op:
        batch_op.create_index("ix_pipeline_run_files_hash_md5", ["hash_md5"], unique=False)
        batch_op.create_index("ix_pipeline_run_files_run_id", ["pipeline_run_id"], unique=False)

    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("idempotency_key", sa.String(length=255), nullable=True))
        batch_op.create_index(
            "ix_pipeline_runs_idempotency", ["pipeline_id", "idempotency_key"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_pipeline_runs_idempotency")
        batch_op.drop_column("idempotency_key")

    with op.batch_alter_table("pipeline_run_files", schema=None) as batch_op:
        batch_op.drop_index("ix_pipeline_run_files_run_id")
        batch_op.drop_index("ix_pipeline_run_files_hash_md5")

    op.drop_table("pipeline_run_files")
    # ### end Alembic commands ###
