"""refactor endpoint to use name instead of asset_id

Revision ID: 7c8904a69992
Revises: ce8479ee3a0b
Create Date: 2026-07-06 15:37:10.432043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8904a69992'
down_revision: Union[str, Sequence[str], None] = 'ce8479ee3a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_lineages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('source_object_id', sa.String(length=36), nullable=False),
    sa.Column('destination_object_id', sa.String(length=36), nullable=False),
    sa.Column('column_mappings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_object_id'], ['data_objects.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['source_object_id'], ['data_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_schema_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['data_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_schema_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_schema_versions_object_id'), ['object_id'], unique=False)

    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint('uq_endpoints_name', ['name'])
        batch_op.drop_column('asset_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'data_assets', ['asset_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('catalog_schema_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_schema_versions_object_id'))

    op.drop_table('catalog_schema_versions')
    op.drop_table('catalog_lineages')
    # ### end Alembic commands ###
