"""add_data_elements_table_remove_elements_json

Revision ID: 83bd97ad3479
Revises: 7c8904a69992
Create Date: 2026-07-07 09:56:18.634704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "83bd97ad3479"
down_revision: Union[str, Sequence[str], None] = "7c8904a69992"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_elements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column("destination_type", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("policy_tag", sa.String(length=100), nullable=True),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.Column("is_computed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["object_id"], ["data_objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_elements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_data_elements_object_id"), ["object_id"], unique=False)

    op.drop_table("catalog_lineages")
    with op.batch_alter_table("data_objects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("policy_tags_json", sa.String(length=2000), nullable=False))
        batch_op.drop_column("elements")
        batch_op.drop_column("policy_tags")

    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_pipelines_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.drop_constraint("uq_pipelines_name", type_="unique")

    with op.batch_alter_table("data_objects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("policy_tags", sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column("elements", sqlite.JSON(), nullable=False))
        batch_op.drop_column("policy_tags_json")

    op.create_table(
        "catalog_lineages",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("pipeline_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("source_object_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("destination_object_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("column_mappings", sqlite.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_object_id"],
            ["data_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_object_id"],
            ["data_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_elements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_elements_object_id"))

    op.drop_table("data_elements")
    # ### end Alembic commands ###
