"""rename_pipeline_assets_to_canonical_names

Revision ID: 96cef173ce8b
Revises: 14f90f1ed51b
Create Date: 2026-09-24 14:43:16.460600

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96cef173ce8b"
down_revision: str | Sequence[str] | None = "14f90f1ed51b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_asset_name", sa.String(length=255), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "destination_asset_name", sa.String(length=255), nullable=False, server_default=""
            )
        )
        batch_op.drop_column("destination_asset")
        batch_op.drop_column("source_asset")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipelines", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source_asset", sa.VARCHAR(length=255), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column(
                "destination_asset", sa.VARCHAR(length=255), nullable=False, server_default=""
            )
        )
        batch_op.drop_column("destination_asset_name")
        batch_op.drop_column("source_asset_name")

    # ### end Alembic commands ###
