"""add_pipeline_runs_table

Revision ID: b36d951a65f2
Revises: ee9ea149c298
Create Date: 2026-07-02 09:09:37.202944

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b36d951a65f2"
down_revision: str | Sequence[str] | None = "ee9ea149c298"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pipeline_runs",
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.add_column(
        "pipeline_runs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("pipeline_name", sa.String(length=255), nullable=False, server_default=""),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("pipeline_type", sa.String(length=50), nullable=False, server_default=""),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("dag_run_id", sa.String(length=255), nullable=False, server_default=""),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column(
            "last_run_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.add_column(
        "pipeline_runs", sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("pipeline_runs", sa.Column("failed_task", sa.String(length=255), nullable=True))
    op.add_column(
        "pipeline_runs",
        sa.Column("optional_failures", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("quality_violations", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "pipeline_runs",
        sa.Column("sla_breached", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "pipeline_runs", sa.Column("sla_minutes", sa.Integer(), nullable=False, server_default="90")
    )

    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.drop_column("run_id")
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    op.create_index(
        op.f("ix_pipeline_runs_pipeline_id"), "pipeline_runs", ["pipeline_id"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_runs_started_at"), "pipeline_runs", ["started_at"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_time", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("end_time", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("run_id", sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f("ix_pipeline_runs_started_at"))
        batch_op.drop_index(batch_op.f("ix_pipeline_runs_pipeline_id"))
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=30),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
