"""Add discovery runs and drift approvals

Revision ID: ce8479ee3a0b
Revises: b36d951a65f2
Create Date: 2026-07-02 11:17:13.876513

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce8479ee3a0b"
down_revision: str | Sequence[str] | None = "b36d951a65f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("triggered_by", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("objects_discovered", sa.Integer(), nullable=False),
        sa.Column("fields_discovered", sa.Integer(), nullable=False),
        sa.Column("snapshots_json", sa.JSON(), nullable=False),
        sa.Column("drift_events_json", sa.JSON(), nullable=False),
        sa.Column("policy_suggestions_json", sa.JSON(), nullable=False),
        sa.Column("auto_descriptions_json", sa.JSON(), nullable=False),
        sa.Column("soft_failures", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discovery_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discovery_runs_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "drift_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("discovery_run_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=True),
        sa.Column("change_type", sa.String(length=50), nullable=False),
        sa.Column("severity_description", sa.String(length=2000), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["discovery_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drift_approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drift_approvals_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_drift_approvals_discovery_run_id"), ["discovery_run_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drift_approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drift_approvals_discovery_run_id"))
        batch_op.drop_index(batch_op.f("ix_drift_approvals_asset_id"))

    op.drop_table("drift_approvals")
    with op.batch_alter_table("discovery_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discovery_runs_asset_id"))

    op.drop_table("discovery_runs")
    # ### end Alembic commands ###
