"""add_object_metadata_and_is_primary_key

Revision ID: f7d6f51e45d7
Revises: 4b27a559ffb4
Create Date: 2026-07-21 14:27:37.590961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7d6f51e45d7"
down_revision: str | Sequence[str] | None = "4b27a559ffb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_elements", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_primary_key", sa.Boolean(), nullable=False))

    with op.batch_alter_table("data_objects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("object_metadata_json", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("data_objects", schema=None) as batch_op:
        batch_op.drop_column("object_metadata_json")

    with op.batch_alter_table("data_elements", schema=None) as batch_op:
        batch_op.drop_column("is_primary_key")

    # ### end Alembic commands ###
