from __future__ import annotations

import os
from datetime import datetime, timezone

import yaml
from jinja2 import Environment, FileSystemLoader

_TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")


class DagGenerator:
    """Generates Airflow 3 Python DAG code from Pipeline YAML definition."""

    def __init__(self) -> None:
        self._env = Environment(
            loader=FileSystemLoader(_TEMPLATES_DIR),
            autoescape=False,
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def generate(self, pipeline_yaml: str) -> str:
        pipeline_dict = yaml.safe_load(pipeline_yaml)
        # Assuming the YAML has a 'pipeline' root key as generated by PipelineYamlGenerator
        pipeline_config = pipeline_dict.get("pipeline", pipeline_dict)

        pipeline_type = pipeline_config.get("type", "ingestion")
        template_name = f"{pipeline_type}_dag.py.j2"

        template = self._env.get_template(template_name)

        # Add generated metadata
        now = datetime.now(tz=timezone.utc).isoformat()

        return template.render(
            pipeline=pipeline_config,
            template_version="1.0.0",
            generated_at=now,
            commit_hash="local",
        )
