from __future__ import annotations

import os
from datetime import UTC, datetime
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader

_TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")


def _normalize_paths(data: Any) -> Any:
    """Recursively normalize Windows backslashes in strings to forward slashes."""
    if isinstance(data, str):
        if "\\" in data:
            return data.replace("\\", "/")
        return data
    if isinstance(data, dict):
        return {k: _normalize_paths(v) for k, v in data.items()}
    if isinstance(data, list):
        return [_normalize_paths(item) for item in data]
    return data


class DagGenerator:
    """Generates Airflow 3 Python DAG code from Pipeline YAML definition."""

    def __init__(self) -> None:
        self._env = Environment(
            loader=FileSystemLoader(_TEMPLATES_DIR),
            autoescape=False,
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self._env.filters["sanitize_identifier"] = lambda s: "".join(
            c if c.isalnum() or c == "_" else "_" for c in str(s)
        )

    def generate(self, pipeline_yaml: str) -> str:
        pipeline_dict = yaml.safe_load(pipeline_yaml)
        # Assuming the YAML has a 'pipeline' root key as generated by PipelineYamlGenerator
        pipeline_config = pipeline_dict.get("pipeline", pipeline_dict)
        pipeline_config = _normalize_paths(pipeline_config)

        pipeline_type = pipeline_config.get("type", "ingestion")
        template_name = f"{pipeline_type}_dag.py.j2"

        template = self._env.get_template(template_name)

        # Add generated metadata
        now = datetime.now(tz=UTC).isoformat()

        return template.render(
            pipeline=pipeline_config,
            template_version="1.0.0",
            generated_at=now,
            commit_hash="local",
        )
