from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable


@dataclass
class DwhLoadResult:
    """Result of a bulk load operation into the Data Warehouse."""

    rows_loaded: int
    engine: str
    checksum: str | None = None


@runtime_checkable
class DwhLoaderAdapter(Protocol):
    """
    Protocol for Data Warehouse loading adapters.

    Each DWH engine (BigQuery, Databricks, Snowflake) implements this interface.
    Ensures that the load_to_data_warehouse callback remains agnostic to the destination.
    """

    def load(
        self,
        *,
        staging_path: str,
        schema_path: str,
        file_format: str,
        connection_metadata: dict[str, Any],
        resolved_credentials: dict[str, Any] | None = None,
    ) -> DwhLoadResult:
        """Executes the bulk load of the structured file into the target DWH.

        Args:
            staging_path: Path to the Parquet/Avro file generated by the Compute Engine.
            schema_path: Path to the schema.json containing column metadata.
            file_format: Input file format: "parquet" or "avro".
            connection_metadata: Non-sensitive metadata (host, dataset, table) injected
                at compile-time by the DAG Generator.
            resolved_credentials: Credentials resolved at runtime via Vault (only
                when auth_method="vault"). None when auth_method="iam".

        Returns:
            DwhLoadResult with loaded rows count and used engine.
        """
        ...
